### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by nunojesus** [mosajjal/h3#1]
Hi,
I have read your work so I decided to creat a logo for you. I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

I used the colours of your website.

Greetings
![h3](https://user-images.githubusercontent.com/34600369/39478352-1c178966-4d5a-11e8-9390-685760bee1ad.png)

**Comment by mosajjal** [comment]
wow this is amazing and flattering! Thank you so much! I'm gonna think of a way to use them properly with your help.

**Comment by nunojesus** [comment]
Im happy that you like it, if you want some help in something, just say it.

**Comment by nunojesus** [comment]
@mosajjal did you choose which of the logos you prefer to be the main one?

**Comment by mosajjal** [comment]
yeah I kinda did! The second one from the top and the right hand side. That's my favorite :) thanks

**Comment by nunojesus** [comment]
I like that too, now I will prepair de png files for you.

**Comment by mosajjal** [comment]
Thanks :) Closing this since it's merged

**Comment by atlury** [comment]
wow the logos are nice.....i wish i knew someone with those skills
