### ISSUE TITLE
[q] im may use this for create kernel headers on ubuntu for opi zero lts (H3)?

### ISSUE THREAD

**Issue by whoim2** [mosajjal/h3#4]
Hello. I need make wifi driver, this need kernel header, i find any way for this process. Maybe, i may compile 3.11 kernel from this repo?
Help please.

**Comment by mosajjal** [comment]
Hi. This repo is fully unmaintained unfortunately. I suggest you look at `armbian` or similar. I'll mark the repo as archive.
